### ISSUE TITLE
Question about Sin/Sout pull down resistor

### ISSUE THREAD

**Issue by littlebalup** [MasonStooksbury/Open-Source-N64-Expansion-Pak#1]
Hi,
I'm looking to recycle a pair of original 2MB RDRAM18 from a ruined N64 motherboard to make an homemade Expansion Pack for another machine.
This project looks exacltly what I need thanks.
I didn't deep dived into N64 rdram / expansion pack / jumper pack architecture yet but I'm already seeing something strange to me on your schematic: 
You connected the 510ohm resistor to the S_in line of the U2 chip (which should be connected to the S_out of the last rdram chip of the motherboard via your edge connector pin 31 I guess).
That resistor shouldn't be connected to the U2 S_out / U1 S_in line instead? Or even to the U1 S_out? As I understand, U1 is the last rdram chip of the serie.

![image](https://github.com/MasonStooksbury/Open-Source-N64-Expansion-Pak/assets/6732619/22a833f0-0fdb-4a3e-b0da-1d586f8be292)

or

![image](https://github.com/MasonStooksbury/Open-Source-N64-Expansion-Pak/assets/6732619/b410ef28-22ae-4c04-ad85-be95a4256075)

I planed to trace Sin / Sout of my motherboard, jumper pack and of an original expansion pack to better understand this. But your thought whould be appreciated too.

**Comment by MasonStooksbury** [comment]
Hey, thank you so much for looking into this! I'm currently at a family event but will dive deeper into this when I get home tonight. I'll report back with any findings!

**Comment by MasonStooksbury** [comment]
So I couldn't stay away from this and I think you may have caught an issue lol I've been having intermittent and often dangerous consequences with this pak and I wonder if this could be the issue. Once I get home I'll try and create bodge for the board and see if anything changes.

**Comment by littlebalup** [comment]
I'm not even sure that R13 resistor is necessary. I'm not seeing it on official NUS-RMC-10 expansion pak board or on jumper pak. Where does it come from?

**Comment by MasonStooksbury** [comment]
It's not on early versions, you are correct. However, they added it in later versions (my best guess is for stability since RDRAM is incredibly finicky when it comes to termination resistors and stuff). You can find a more detailed write up I made over on Reddit. I think it's the last point in that update

https://www.reddit.com/r/n64/comments/1042myr/open_source_expansion_pak_update_and_help_wanted/

**Comment by littlebalup** [comment]
> It's not on early versions, you are correct. However, they added it in later versions (my best guess is for stability since RDRAM is incredibly finicky when it comes to termination resistors and stuff). You can find a more detailed write up I made over on Reddit. I think it's the last point in that update
> 
> https://www.reddit.com/r/n64/comments/1042myr/open_source_expansion_pak_update_and_help_wanted/

Got it. Interesting. Do you have an idea of that board revision? NUS-RMC-##?

https://photos.google.com/share/AF1QipO4aWchxXKLJYNMali1IsJKWliu4HdxEcPb6OW7lAtu6cvlLj7B-13hjv64Gd0HzA?key=ZkxzZEhpbTB6dldtTHBxZl82NTdtT3dVRzJsa19R

**Comment by MasonStooksbury** [comment]
> > It's not on early versions, you are correct. However, they added it in later versions (my best guess is for stability since RDRAM is incredibly finicky when it comes to termination resistors and stuff). You can find a more detailed write up I made over on Reddit. I think it's the last point in that update
> > https://www.reddit.com/r/n64/comments/1042myr/open_source_expansion_pak_update_and_help_wanted/
> 
> Got it. Interesting. Do you have an idea of that board revision? NUS-RMC-##?
> 
> https://photos.google.com/share/AF1QipO4aWchxXKLJYNMali1IsJKWliu4HdxEcPb6OW7lAtu6cvlLj7B-13hjv64Gd0HzA?key=ZkxzZEhpbTB6dldtTHBxZl82NTdtT3dVRzJsa19R

I'll do you one better! Here's a spreadsheet where I kept track of everything I could find (along with what people submitted)

https://docs.google.com/spreadsheets/d/1Ax2_HSiqV_8NazG6FtHj_OeQ6TdKuoSON_qMUd4TySQ/edit?usp=sharing

**Comment by littlebalup** [comment]
I'll definitely open one of mine to check tonight. I'll also look at the motherboard RDRAM chips, specially the associated decoupling caps and pull-up/down resistors if any.
Meanwhile I reversed engineered the Jumper pak to better understand the basic RDRAM bus termination. Here are my schematics if needed for future reference.
https://www.dropbox.com/scl/fi/4soicun3c8norochmqen7/Jumper-Pak-NUS-RTC-03.pdf?rlkey=pripa0h8rd16a2pdlet6sqd39&dl=0
https://www.dropbox.com/scl/fi/8s8tj27t9gtrvfqb0hmch/Jumper-Pak-NUS-RTC-10.pdf?rlkey=gbpn2npru9ocsmjf40d59wgzg&dl=0

Note: C1-C4 values are wrong in my schematic. 3.3uF is the capacitance measured in circuit. So the total for the four caps. The good value for each should be 3.3/4= 0.82uF (820nF).
I'll correct this later.

**Comment by ArtFellResist** [comment]
> > > It's not on early versions, you are correct. However, they added it in later versions (my best guess is for stability since RDRAM is incredibly finicky when it comes to termination resistors and stuff). You can find a more detailed write up I made over on Reddit. I think it's the last point in that update
> > > https://www.reddit.com/r/n64/comments/1042myr/open_source_expansion_pak_update_and_help_wanted/
> > 
> > 
> > Got it. Interesting. Do you have an idea of that board revision? NUS-RMC-##?
> > https://photos.google.com/share/AF1QipO4aWchxXKLJYNMali1IsJKWliu4HdxEcPb6OW7lAtu6cvlLj7B-13hjv64Gd0HzA?key=ZkxzZEhpbTB6dldtTHBxZl82NTdtT3dVRzJsa19R
> 
> I'll do you one better! Here's a spreadsheet where I kept track of everything I could find (along with what people submitted)
> 
> https://docs.google.com/spreadsheets/d/1Ax2_HSiqV_8NazG6FtHj_OeQ6TdKuoSON_qMUd4TySQ/edit?usp=sharing

Idk if you already seen this, but I've found this forum where this user posted a lot of different "Expansion Pack"s, both sides

https://bitbuilt.net/forums/index.php?threads/n64-expansion-paks-ram-part-numbers.3943/

**Comment by MasonStooksbury** [comment]
> Hi, I'm looking to recycle a pair of original 2MB RDRAM18 from a ruined N64 motherboard to make an homemade Expansion Pack for another machine. This project looks exacltly what I need thanks. I didn't deep dived into N64 rdram / expansion pack / jumper pack architecture yet but I'm already seeing something strange to me on your schematic: You connected the 510ohm resistor to the S_in line of the U2 chip (which should be connected to the S_out of the last rdram chip of the motherboard via your edge connector pin 31 I guess). That resistor shouldn't be connected to the U2 S_out / U1 S_in line instead? Or even to the U1 S_out? As I understand, U1 is the last rdram chip of the serie.
> 
> ![image](https://private-user-images.githubusercontent.com/6732619/300211194-22a833f0-0fdb-4a3e-b0da-1d586f8be292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTg5MjUsIm5iZiI6MTcxNjI1ODYyNSwicGF0aCI6Ii82NzMyNjE5LzMwMDIxMTE5NC0yMmE4MzNmMC0wZmRiLTRhM2UtYjBkYS0xZDU4NmY4YmUyOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMDIzMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTcwNjUyMzMxNWFhYzlmNDA2MDg0NzczZGRhMTdjMWFlZDM5NzczYmM3MzY0YmViNjMyMzRiMDA4ZTEwNWU0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n8nyRVIBErNwYV6_6slajIMxFMn7cq0YXLiNtxGadVk)
> 
> or
> 
> ![image](https://private-user-images.githubusercontent.com/6732619/300211220-b410ef28-22ae-4c04-ad85-be95a4256075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTg5MjUsIm5iZiI6MTcxNjI1ODYyNSwicGF0aCI6Ii82NzMyNjE5LzMwMDIxMTIyMC1iNDEwZWYyOC0yMmFlLTRjMDQtYWQ4NS1iZTk1YTQyNTYwNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMDIzMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWMzYWZkOGE4ODhkYTU3NTk2ZDNkMTQwOGQyZjI5ZDYwZjMzMmMwNGQyMGIyYzZmNDZlMjA2Njc1ZGIyZTk2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bsrDiOGwryePtzDliDUM7tXne2bUPLWA74WcQnEO6F0)
> 
> I planed to trace Sin / Sout of my motherboard, jumper pack and of an original expansion pack to better understand this. But your thought whould be appreciated too.

Finally got around to properly testing this (had to get more N64s, got busy, etc)

From researching the board I had that works, as well as the datasheets for the RDRAM chips themselves, I'm reasonably confident that the resistor goes on pin 20 (Serial Input or "SIn").

With that, I tried your first diagram to no avail :/

N64 works fine with jumper pak, try my custom pak and it doesn't work, try the jumper pak again: stone dead. Closing this for now and will do further testing
