### ISSUE TITLE
C1 Not Connected to Ground

### ISSUE THREAD

**Issue by Arthrimus** [MasonStooksbury/Open-Source-N64-Expansion-Pak#2]
Hello, I was looking over your PCB file and noticed that C1 does not connect to the ground pour. In the schematic it is connected, just not on the board file. I corrected it on my end, as well as added an extra row of 1.8uf capacitors closer to the second ram chip. I added a few of these to my most recent PCB order and so far my testing has shown it to be stable with these modifications, but I did see the other issue about the Sin/Sout resistor, so I'm interested to see what comes of that.

**Comment by MasonStooksbury** [comment]
No. Freaking. Way... I cannot believe I missed this. I must not have had the nets setup correctly in KiCad so I never got a warning about it.

Thank you so much for catching this, I cannot wait to bodge this and see if it helps the issues I've been having.

**Comment by MasonStooksbury** [comment]
Fixed this in [this commit](https://github.com/MasonStooksbury/Open-Source-N64-Expansion-Pak/commit/a4516c25a9957c73ee85d103e183fb76fd3b955a). Thank you so much for catching that and posting an issue. 

I also posted another comment regarding that extra resistor. TL;DR, I have no proof that it's necessary other than the fact that Nintendo added it to later revisions of their board. So they must have done some testing and determined it to be important. 

I'm gonna go ahead and close this, but please feel free to continue the conversation regarding the resistor over on that issue!
